package com.mark.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-31T19:51:19.385+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://demo.mark.com/", name = "OrderWebServiceI")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderWebServiceI {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://demo.mark.com/", className = "com.mark.demo.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://demo.mark.com/", className = "com.mark.demo.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
