package com.mark.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-31T19:51:19.422+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "OrderWebServiceImplService", 
                  wsdlLocation = "http://localhost:8080/demo-web-service-A/webservice/orderWebService?wsdl",
                  targetNamespace = "http://demo.mark.com/") 
public class OrderWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.mark.com/", "OrderWebServiceImplService");
    public final static QName OrderWebServiceImplPort = new QName("http://demo.mark.com/", "OrderWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/demo-web-service-A/webservice/orderWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/demo-web-service-A/webservice/orderWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OrderWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderWebServiceI
     */
    @WebEndpoint(name = "OrderWebServiceImplPort")
    public OrderWebServiceI getOrderWebServiceImplPort() {
        return super.getPort(OrderWebServiceImplPort, OrderWebServiceI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWebServiceI
     */
    @WebEndpoint(name = "OrderWebServiceImplPort")
    public OrderWebServiceI getOrderWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OrderWebServiceImplPort, OrderWebServiceI.class, features);
    }

}
